// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWE8d09BjqjIT3jIC5xkBJqA4a7SsC2_w',
    appId: '1:402429123677:web:d748d4ec0c499bf57a01b4',
    messagingSenderId: '402429123677',
    projectId: 'holbegram-94ff6',
    authDomain: 'holbegram-94ff6.firebaseapp.com',
    storageBucket: 'holbegram-94ff6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_BRtke8iOuIuEFC-7iQZxNgNQ7LHcnn8',
    appId: '1:402429123677:android:082686cab4f7e65e7a01b4',
    messagingSenderId: '402429123677',
    projectId: 'holbegram-94ff6',
    storageBucket: 'holbegram-94ff6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyfaoepDqX9btdup18TGGODJtl545rXyA',
    appId: '1:402429123677:ios:adfddee72fe315187a01b4',
    messagingSenderId: '402429123677',
    projectId: 'holbegram-94ff6',
    storageBucket: 'holbegram-94ff6.appspot.com',
    iosBundleId: 'com.atlas.holbegram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyfaoepDqX9btdup18TGGODJtl545rXyA',
    appId: '1:402429123677:ios:aae2f7f76ba8d04f7a01b4',
    messagingSenderId: '402429123677',
    projectId: 'holbegram-94ff6',
    storageBucket: 'holbegram-94ff6.appspot.com',
    iosBundleId: 'com.example.holbegram.RunnerTests',
  );
}
